# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

stages:
- stage: build_test
  jobs:
  - job: build_test
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build

- stage: deploy
  dependsOn: build_test
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/releases')
  jobs:
  - job: deploy_to_west
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploying West
    
- stage: prod_verify
  dependsOn:
  - deploy
  jobs:
  - job: verify
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Verifying deploy



# jobs:
#   frontend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Use Node.js 16.x
#         uses: actions/setup-node@v3

#       - name: npm install
#         run : npm install

#       - name: npm run build --if-present
#         run : npm run build

#       - name: npm test
#         run : npm test

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Logining in Docker hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}      

#       - name: Build and push
#         uses: docker/build-push-action@v2.10.0
#         with:
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/numerical:last
          

#   backend:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Step 1"
